### ISSUE TITLE
Quickly switching between days with all PM2.5 displaying can lag >1 minute and fail to display

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/plume-viz-website#7]
In Chrome, turn on developer tools and select Network tab
Select All PM2.5 monitors
Quickly switch between 5+ days more than a week apart

Observe 30+ seconds before PM2.5 from the last day displays

Observe many of the PM2.5 sensors from that day may not display, for example, this day is only showing a small subset of sensors on the left

![image](https://user-images.githubusercontent.com/324851/116346455-506bdf80-a7b8-11eb-9ea2-bbb49b502a92.png)

Observe the network tab showing many failed requests, and succeeding requests taking 30+ seconds:
![image](https://user-images.githubusercontent.com/324851/116346541-7ee9ba80-a7b8-11eb-9a4b-a34bae234d04.png)

If you have difficulty reproducing, I can send a screencast I recorded.  (It's 1.5GB so cannot attach to this report.)

When we switch days, is it possible to cancel the ajax requests that are incomplete?

Is it possible that the errors we're receiving are from the ESDR server?  Might need to work with Chris to diagnose.

**Comment by dognotdog** [comment]
It looks like `XMLHttpRequest.abort()` could work to clear the queue in the browser, but it needs to be put in the right place to not screw things up. Right now, all requests for the daily data are simply kicked down to the browser, and aren't cancelled when the date changes, due to the layers involved in this. As the results are cached, they are simply executed and ready for when the date is switched back, but the request logic is handled in each "map marker" and not globally.

However, there is a mechanism that is being used to remove markers from the map on a sensor layer switch, and possibly the same mechanism could be employed for date changes with the added `abort()` call.

**Comment by dognotdog** [comment]
Fixed in f8d29fa4c694bcd40a9d439cda846e792fd1ee82 by cancelling all pending requests on date switch.
